spring:

  datasource:
    url: jdbc:mysql://localhost:5432/sandbox
    username: guest_user
    password: guest_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8