spring:

  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8